### PR TITLE
(MODULES-3631) msync Gemfile for 1.9 frozen strings

### PR DESCRIPTION
**Pull request by hunner**
https://github.com/puppetlabs/modulesync_configs/pull/102

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Hi @hunner 

Why is `:platforms => 'ruby'` set? Since this is a Gemfile, wouldn't the platform always be ruby?

**Comment by hunner** [comment]
@ghoneycutt platform 'ruby' is not the platform on windows. It doesn't make sense due to historical reasons. We are trying to make our modulesync_config templates generic across windows and non-windows modules, so that's why this change is here.

**Comment by ghoneycutt** [comment]
Ah, I would have figured it to be something like `:platforms => 'posix'` or `'windows'` or something like that. If I'm understanding correctly, by putting `:platforms => 'ruby'` you mean, run everywhere except windows? Am I understanding correctly?

Thank you for the explanation!

**Comment by hunner** [comment]
@ghoneycutt Yeah, it's to exclude the gem on windows.

The reason is that all of the "windows" platforms don't exist on older bundler versions so it's just normal practice. https://github.com/bundler/bundler/blob/9f414c55be8b749f46a0470277f14572c5246c03/lib/bundler/current_ruby.rb#L23

**Pull request merged**
